import { AGENT_DOCS_LAST_UPDATED } from '../../config/agents.js';
import { getAgentToolCatalog } from '../../lib/agentTools.js';

export function GET() {
    const catalog = getAgentToolCatalog();
    const body = [
        '# TaskTime Pro Agent Skill',
        '',
        `Updated: ${AGENT_DOCS_LAST_UPDATED}`,
        '',
        '## Purpose',
        '',
        'Use this skill when a user asks an AI agent to work with TaskTime Pro: local-first task management, time tracking, expenses, reports, invoices, project quotes, planner notes, backups, sync settings, or account data.',
        '',
        '## Public References',
        '',
        '- Agent docs: https://tasktime.pro/agents/',
        '- Quickstart: https://tasktime.pro/agents/quickstart/',
        '- Security model: https://tasktime.pro/agents/security/',
        '- MCP tool reference: https://tasktime.pro/agents/tools/',
        '- Machine-readable MCP tools: https://tasktime.pro/agents/mcp-tools.json',
        '- Bridge discovery manifest: https://tasktime.pro/.well-known/tasktime-agent.json',
        '- Debugging guide: https://tasktime.pro/agents/debugging/',
        '- OpenClaw bundle package: `@tasktimepro/openclaw`',
        '- Bridge binary package: `@tasktimepro/agent-bridge`',
        '',
        '## Operating Rules',
        '',
        '- Prefer TaskTime Pro MCP tools over browser UI automation.',
        '- Treat TaskTime Pro as local-first customer data. Do not ask users to reset browser data or Drive state as a normal fix.',
        '- Launch `tasktime-agent-bridge --app-url <TaskTime Pro URL>` when local MCP access is needed.',
        '- Require a running paired TaskTime Pro browser app session before reading or mutating local TaskTime Pro data.',
        '- Keep first-use access explicit: the user approves Account > Agent Access.',
        '- Respect granted scopes and call `tools/list` at runtime because available tools depend on bridge scopes.',
        '- Use a valid exact-input TaskTime Pro approval token or browser-visible approval for sensitive actions.',
        '- Do not expose the bridge outside loopback or through tunnels.',
        '- Use UI automation only for visual validation or unsupported workflows.',
        '',
        '## Current Bridge Shape',
        '',
        '- Binary: `tasktime-agent-bridge`',
        '- Transport: MCP stdio JSON-RPC',
        '- Default scopes: `read`, `write`, `navigation`',
        '- Optional scopes: `billing`, `export`, `email`',
        `- Public tool count: ${catalog.toolCount}`,
        '- OpenClaw bundle MCP tools may be exposed with a `tasktime__` prefix, for example `tasktime__list_projects`.',
        '',
        '## Useful First Calls',
        '',
        '- `list_projects` to inspect available projects.',
        '- `list_clients` to inspect client records.',
        '- `get_active_timers` to inspect running timers.',
        '- `create_task` to create scoped work inside an existing project.',
        '- `start_timer` to begin time tracking.',
        '- `find_unbilled_time` or `preview_invoice_from_unbilled_work` before invoice drafting.',
        '- `open_project_view`, `open_invoice_view`, or `open_reports_view` to bring the user to a review screen.',
        '',
        '## Recovery',
        '',
        'If a tool call returns an unavailable app-session error with `launch_tasktime`, open or guide the user to TaskTime Pro, pair Account > Agent Access, then retry. Do not treat this as a generic failure.',
        '',
        'Use DebugBundle only for runtime or customer-facing incidents, endpoint downtime, health checks, webhook or notification failures, noisy captured incidents, or symptoms likely to have generated captured events. For deterministic local code, docs, UI, refactor, or test failures, inspect source and tests first.',
        '',
    ].join('\n');

    return new Response(body, {
        headers: {
            'Content-Type': 'text/markdown; charset=utf-8',
        },
    });
}
