/**
 * Icon abstraction layer
 * Centralizes all icon imports for easy library swapping
 * Currently using: lucide-react
 */
export {
    AlertCircle as ExclamationCircleIcon,
    AlertTriangle as ExclamationTriangleIcon,
    Archive as ArchiveBoxIcon,
    ArchiveRestore as ArchiveRestoreIcon,
    ArrowLeft as ArrowLeftIcon,
    ArrowUpDown as SortIcon,
    BarChart3 as ChartBarIcon,
    Banknote as BanknotesIcon,
    Building2 as BuildingOfficeIcon,
    CalendarDays as CalendarDaysIcon,
    Check as CheckIcon,
    Cloud as CloudIcon,
    CloudCheck as CloudCheckIcon,
    CloudDownload as CloudDownloadIcon,
    CloudUpload as CloudUploadIcon,
    CloudSync as CloudSyncIcon,
    CloudCog as CloudCogIcon,
    ChevronDown as ChevronDownIcon,
    ChevronLeft as ChevronLeftIcon,
    ChevronRight as ChevronRightIcon,
    ChevronUp as ChevronUpIcon,
    ClipboardCheck as ClipboardDocumentCheckIcon,
    Clock as ClockIcon,
    Copy as DocumentDuplicateIcon,
    CreditCard as CreditCardIcon,
    DollarSign as CurrencyDollarIcon,
    Eye as EyeIcon,
    EyeOff as EyeOffIcon,
    FileCheck as DocumentCheckIcon,
    FileText as DocumentTextIcon,
    Info as InformationCircleIcon,
    Moon as MoonIcon,
    MoreHorizontal as MoreHorizontalIcon,
    Search as MagnifyingGlassIcon,
    Pause as PauseIcon,
    Pencil as PencilIcon,
    Play as PlayIcon,
    Plus as PlusIcon,
    LogOut as SignOutIcon,
    Rocket as RocketLaunchIcon,
    RefreshCw as ArrowPathIcon,
    Settings as CogIcon,
    Square as StopIcon,
    Sun as SunIcon,
    Trash2 as TrashIcon,
    Upload as ArrowUpTrayIcon,
    User as UserCircleIcon,
    Users as UserGroupIcon,
    WifiOff as WifiOffIcon,
    X as XMarkIcon,
    Download as ArrowDownTrayIcon,
} from "lucide-react";
